export interface ProjectItemData {
  title: string;
  subTitle: string;
  tech: string[];
  link: string;
  imageUrl?: string;
  imageSize?: "small" | "medium" | "large";
  images?: string[]; // 갤러리용 이미지들
  achievements?: string[];
  roles?: string[];
  // keyFeatures?: string[];
  // reflection: string;
}

export const projects: ProjectItemData[] = [
  {
    title: "LLM-based Diagnosis System of Math Problem Solving Skills",
    subTitle: "",
    tech: ["Prompt Engineering", "FastAPI", "LangFlow", "React"],
    link: "#",
    imageUrl: "",
    imageSize: "medium",
    images: [],
    roles: ["HCI Researcher"],
    // keyFeatures: ["In Progress..."],
    // reflection: "In Progress...",
  },
  {
    title: "Book Nook",
    subTitle: "Large-Print Book Search and Recommendation Service for the Visually Impaired",
    tech: ["Python", "Selenium", "BeautifulSoup"],
    link: "#",
    imageUrl: "/img/BookNook/BookNookLogo.png",
    imageSize: "medium",
    images: [
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0001.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0002.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0003.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0004.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0005.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0006.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0007.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0008.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0009.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0010.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0011.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0012.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0013.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0014.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0015.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0016.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0017.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0018.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0019.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0020.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0021.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0022.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0023.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0024.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0025.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0026.jpg",
      "/img/BookNook/BookNookPPT/BookNookPPT_page-0027.jpg",
    ],
    roles: ["AI Engineer", "Product Manager"],
    // keyFeatures: ["웹 크롤링을 통한 도서 정보 수집", "대형 글씨 도서 필터링", "개인화된 도서 추천 시스템"],
    // reflection: "웹 크롤링을 통한 도서 정보 수집, 대형 글씨 도서 필터링, 개인화된 도서 추천 시스템",
  },
  {
    title: "Foodie Buddy",
    subTitle: "Generative AI–Powered Chat Application Providing Personalized Korean Cuisine Information for Foreigners with Dietary Restrictions",
    tech: ["React Native", "TypeScript"],
    link: "#",
    imageUrl: "/img/FoodieBuddy/FoodieBuddyLogo.png",
    imageSize: "large",
    images: [
      "/img/FoodieBuddy/FoodieBuddy_Poster.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0001.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0002.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0003.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0004.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0005.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0006.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0007.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0008.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0009.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0010.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0011.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0012.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0013.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0014.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0015.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0016.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0017.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0018.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0019.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0020.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0021.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0022.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0023.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0024.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0025.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0026.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0027.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0028.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0029.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0030.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0031.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0032.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0033.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0034.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0035.jpg",
      "/img/FoodieBuddy/FoodieBuddyFinal/FoodieBuddyFinal_page-0036.jpg",
    ],
    achievements: ["🏅 Korea Tourism Data Lab Competition", "🏅 Engineering Capstone Design Contest", "🏅 Graduation Project Contest"],
    roles: ["Frontend Developer", "Product Manager", "UI/UX Designer"],
    // keyFeatures: ["생성형 AI 기반 채팅 기능", "식이 제한을 고려한 맞춤형 추천", "외국인을 위한 한국 음식 정보 제공"],
    // reflection: "생성형 AI 기반 채팅 기능, 식이 제한을 고려한 맞춤형 추천, 외국인을 위한 한국 음식 정보 제공",
  },
  {
    title: "Shopping Mall Review Ratings Classification Project",
    subTitle: "Rating Prediction Project Using Various Machine Learning Models Based on E-Commerce Review Texts",
    tech: ["Python", "Pandas", "Numpy", "Scikit-learn"],
    link: "#",
    imageUrl: "/img/ReviewClassification/ReviewRating.jpg",
    imageSize: "large",
    images: [
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0001.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0002.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0003.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0004.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0005.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0006.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0007.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0008.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0009.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0010.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0011.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0012.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0013.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0014.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0015.jpg",
      "img/ReviewClassification/ReviewClassificationPPT/ReviewClassification_page-0016.jpg",
    ],
    achievements: ["🏅 Outstanding Project"],
    roles: ["AI Engineer"],
    // keyFeatures: ["다양한 머신러닝 모델 비교", "텍스트 전처리 및 특성 추출", "리뷰 텍스트 기반 평점 예측"],
    // reflection: "다양한 머신러닝 모델 비교, 텍스트 전처리 및 특성 추출, 리뷰 텍스트 기반 평점 예측",
  },
  {
    title: "History Run",
    subTitle: "Interactive Historical Tourism Game",
    tech: ["Unity"],
    link: "#",
    imageUrl: "/img/HistoryRun/HistoryRunLogo.png",
    imageSize: "medium",
    images: [
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0001.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0002.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0003.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0004.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0005.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0006.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0007.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0008.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0009.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0010.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0011.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0012.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0013.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0014.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0015.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0016.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0017.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0018.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0019.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0020.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0021.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0022.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0023.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0024.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0025.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0026.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0027.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0028.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0029.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0030.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0031.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0032.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0033.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0034.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0035.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0036.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0037.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0038.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0039.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0040.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0041.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0042.jpg",
      "img/HistoryRun/HistoryRunPPT/HistoryRunPPT_page-0043.jpg",
    ],
    achievements: ["🏅 Outstanding Project"],
    roles: ["Unity Developer", "Product Manager"],
    // keyFeatures: ["인터랙티브 게임플레이", "역사적 장소 탐험", "교육적 콘텐츠와 게임의 결합"],
    // reflection: "인터랙티브 게임플레이, 역사적 장소 탐험, 교육적 콘텐츠와 게임의 결합",
  },
  {
    title: "SSK",
    subTitle: "Private Tutoring Management Service",
    tech: ["React Native", "TypeScript"],
    link: "#",
    imageUrl: "/img/SSK/SSK.png",
    imageSize: "large",
    images: [
      "/img/SSK/SSK.png",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0002.jpg",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0003.jpg",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0004.jpg",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0005.jpg",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0006.jpg",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0007.jpg",
      "/img/SSK/SSKPPT/SSKPPT (1)_page-0008.jpg",
    ],
    roles: ["Frontend Developer", "Product Manager"],
    // keyFeatures: ["과외 관리 시스템", "학생-선생님 매칭", "일정 및 결제 관리"],
    // reflection: "과외 관리 시스템, 학생-선생님 매칭, 일정 및 결제 관리",
  },
  {
    title: "Steady Day",
    subTitle: "Study Group Management Website",
    tech: ["React", "JavaScript", "TypeScript", "Styled Components"],
    link: "#",
    imageUrl: "/img/SteadyDay/SteadyDayLogo.png",
    imageSize: "medium",
    images: [
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0001.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0002.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0003.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0004.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0005.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0006.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0007.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0008.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0009.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0010.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0011.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0012.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0013.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0014.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0015.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0016.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0017.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0018.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0019.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0020.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0021.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0022.jpg",
      "/img/SteadyDay/SteadyDayPPT/SteadyDayPPT_page-0023.jpg",
    ],
    roles: ["Frontend Developer", "Product Manager"],
    // keyFeatures: ["스터디 그룹 생성 및 관리", "멤버 초대 및 관리", "일정 공유 및 알림"],
    // reflection: "스터디 그룹 생성 및 관리, 멤버 초대 및 관리, 일정 공유 및 알림",
  },
  {
    title: "Kiosk Ally",
    subTitle: "Kiosk Education Application for the Elderly",
    tech: ["Figma"],
    link: "#",
    imageUrl: "/img/KioskAlly/KioskAlly2.png",
    imageSize: "large",
    images: [
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0001.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0002.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0003.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0004.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0005.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0006.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0007.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0008.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0009.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0010.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0011.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0012.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0013.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0014.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0015.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0016.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0017.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0018.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0019.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0020.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0021.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0022.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0023.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0024.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0025.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0026.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0027.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0028.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0029.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0030.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0031.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0032.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0033.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0034.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0035.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0036.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0037.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0038.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0039.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0040.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0041.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0042.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0043.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0044.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0045.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0046.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0047.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0048.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0049.jpg",
      "/img/KioskAlly/KioskAllyPPT/KioskAllyPPT_page-0050.jpg",
    ],
    achievements: ["🏅 A+ Grade"],
    roles: ["Product Manager", "UI/UX Designer"],
    // keyFeatures: ["고령자 친화적 UI/UX", "키오스크 사용법 교육", "단계별 가이드 제공"],
    // reflection: "고령자 친화적 UI/UX, 키오스크 사용법 교육, 단계별 가이드 제공",
  },
];
